//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AMTDevice) DeepCopyInto(out *AMTDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AMTDevice.
func (in *AMTDevice) DeepCopy() *AMTDevice {
	if in == nil {
		return nil
	}
	out := new(AMTDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AMTDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AMTDeviceList) DeepCopyInto(out *AMTDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AMTDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AMTDeviceList.
func (in *AMTDeviceList) DeepCopy() *AMTDeviceList {
	if in == nil {
		return nil
	}
	out := new(AMTDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AMTDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AMTDeviceSpec) DeepCopyInto(out *AMTDeviceSpec) {
	*out = *in
	out.ProfileRef = in.ProfileRef
	out.Endpoint = in.Endpoint
	in.Identity.DeepCopyInto(&out.Identity)
	if in.CredentialsRef != nil {
		in, out := &in.CredentialsRef, &out.CredentialsRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AMTDeviceSpec.
func (in *AMTDeviceSpec) DeepCopy() *AMTDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(AMTDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AMTDeviceStatus) DeepCopyInto(out *AMTDeviceStatus) {
	*out = *in
	if in.AllowedControlModes != nil {
		in, out := &in.AllowedControlModes, &out.AllowedControlModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Firmware = in.Firmware
	out.BootCapabilities = in.BootCapabilities
	out.Redirection = in.Redirection
	if in.Inventory != nil {
		in, out := &in.Inventory, &out.Inventory
		*out = new(InventorySummary)
		(*in).DeepCopyInto(*out)
	}
	if in.MachineRef != nil {
		in, out := &in.MachineRef, &out.MachineRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.HardwareRef != nil {
		in, out := &in.HardwareRef, &out.HardwareRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.LastVerifiedTime != nil {
		in, out := &in.LastVerifiedTime, &out.LastVerifiedTime
		*out = (*in).DeepCopy()
	}
	if in.LastRotatedTime != nil {
		in, out := &in.LastRotatedTime, &out.LastRotatedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AMTDeviceStatus.
func (in *AMTDeviceStatus) DeepCopy() *AMTDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(AMTDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AMTProfile) DeepCopyInto(out *AMTProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AMTProfile.
func (in *AMTProfile) DeepCopy() *AMTProfile {
	if in == nil {
		return nil
	}
	out := new(AMTProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AMTProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AMTProfileList) DeepCopyInto(out *AMTProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AMTProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AMTProfileList.
func (in *AMTProfileList) DeepCopy() *AMTProfileList {
	if in == nil {
		return nil
	}
	out := new(AMTProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AMTProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AMTProfileSpec) DeepCopyInto(out *AMTProfileSpec) {
	*out = *in
	if in.CredentialSources != nil {
		in, out := &in.CredentialSources, &out.CredentialSources
		*out = make([]v1.SecretReference, len(*in))
		copy(*out, *in)
	}
	in.Password.DeepCopyInto(&out.Password)
	out.TLS = in.TLS
	in.Redirection.DeepCopyInto(&out.Redirection)
	if in.TimeSync != nil {
		in, out := &in.TimeSync, &out.TimeSync
		*out = new(bool)
		**out = **in
	}
	in.VirtualMedia.DeepCopyInto(&out.VirtualMedia)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AMTProfileSpec.
func (in *AMTProfileSpec) DeepCopy() *AMTProfileSpec {
	if in == nil {
		return nil
	}
	out := new(AMTProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootCapabilities) DeepCopyInto(out *BootCapabilities) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootCapabilities.
func (in *BootCapabilities) DeepCopy() *BootCapabilities {
	if in == nil {
		return nil
	}
	out := new(BootCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Endpoint) DeepCopyInto(out *Endpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Endpoint.
func (in *Endpoint) DeepCopy() *Endpoint {
	if in == nil {
		return nil
	}
	out := new(Endpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareInfo) DeepCopyInto(out *FirmwareInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareInfo.
func (in *FirmwareInfo) DeepCopy() *FirmwareInfo {
	if in == nil {
		return nil
	}
	out := new(FirmwareInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Identity) DeepCopyInto(out *Identity) {
	*out = *in
	if in.MACAddresses != nil {
		in, out := &in.MACAddresses, &out.MACAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Identity.
func (in *Identity) DeepCopy() *Identity {
	if in == nil {
		return nil
	}
	out := new(Identity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InventorySummary) DeepCopyInto(out *InventorySummary) {
	*out = *in
	if in.NICs != nil {
		in, out := &in.NICs, &out.NICs
		*out = make([]NIC, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InventorySummary.
func (in *InventorySummary) DeepCopy() *InventorySummary {
	if in == nil {
		return nil
	}
	out := new(InventorySummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NIC) DeepCopyInto(out *NIC) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NIC.
func (in *NIC) DeepCopy() *NIC {
	if in == nil {
		return nil
	}
	out := new(NIC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PasswordPolicy) DeepCopyInto(out *PasswordPolicy) {
	*out = *in
	if in.Rotation != nil {
		in, out := &in.Rotation, &out.Rotation
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PasswordPolicy.
func (in *PasswordPolicy) DeepCopy() *PasswordPolicy {
	if in == nil {
		return nil
	}
	out := new(PasswordPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedirectionPolicy) DeepCopyInto(out *RedirectionPolicy) {
	*out = *in
	if in.SOL != nil {
		in, out := &in.SOL, &out.SOL
		*out = new(bool)
		**out = **in
	}
	if in.IDER != nil {
		in, out := &in.IDER, &out.IDER
		*out = new(bool)
		**out = **in
	}
	if in.ListenerEnabled != nil {
		in, out := &in.ListenerEnabled, &out.ListenerEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedirectionPolicy.
func (in *RedirectionPolicy) DeepCopy() *RedirectionPolicy {
	if in == nil {
		return nil
	}
	out := new(RedirectionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedirectionStatus) DeepCopyInto(out *RedirectionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedirectionStatus.
func (in *RedirectionStatus) DeepCopy() *RedirectionStatus {
	if in == nil {
		return nil
	}
	out := new(RedirectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSPolicy) DeepCopyInto(out *TLSPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSPolicy.
func (in *TLSPolicy) DeepCopy() *TLSPolicy {
	if in == nil {
		return nil
	}
	out := new(TLSPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMediaPolicy) DeepCopyInto(out *VirtualMediaPolicy) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnforceSecureBoot != nil {
		in, out := &in.EnforceSecureBoot, &out.EnforceSecureBoot
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMediaPolicy.
func (in *VirtualMediaPolicy) DeepCopy() *VirtualMediaPolicy {
	if in == nil {
		return nil
	}
	out := new(VirtualMediaPolicy)
	in.DeepCopyInto(out)
	return out
}
