//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneEndpoint) DeepCopyInto(out *ControlPlaneEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneEndpoint.
func (in *ControlPlaneEndpoint) DeepCopy() *ControlPlaneEndpoint {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosClusterConfig) DeepCopyInto(out *TalosClusterConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosClusterConfig.
func (in *TalosClusterConfig) DeepCopy() *TalosClusterConfig {
	if in == nil {
		return nil
	}
	out := new(TalosClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TalosClusterConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosClusterConfigSpec) DeepCopyInto(out *TalosClusterConfigSpec) {
	*out = *in
	if in.Talos != nil {
		in, out := &in.Talos, &out.Talos
		*out = new(TalosConfig)
		**out = **in
	}
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosClusterConfigSpec.
func (in *TalosClusterConfigSpec) DeepCopy() *TalosClusterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TalosClusterConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosConfig) DeepCopyInto(out *TalosConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosConfig.
func (in *TalosConfig) DeepCopy() *TalosConfig {
	if in == nil {
		return nil
	}
	out := new(TalosConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosWorkerNodeConfig) DeepCopyInto(out *TalosWorkerNodeConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosWorkerNodeConfig.
func (in *TalosWorkerNodeConfig) DeepCopy() *TalosWorkerNodeConfig {
	if in == nil {
		return nil
	}
	out := new(TalosWorkerNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TalosWorkerNodeConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosWorkerNodeConfigSpec) DeepCopyInto(out *TalosWorkerNodeConfigSpec) {
	*out = *in
	if in.Talos != nil {
		in, out := &in.Talos, &out.Talos
		*out = new(TalosConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosWorkerNodeConfigSpec.
func (in *TalosWorkerNodeConfigSpec) DeepCopy() *TalosWorkerNodeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TalosWorkerNodeConfigSpec)
	in.DeepCopyInto(out)
	return out
}
